### ISSUE TITLE
Unable to set account password and/or remove GitHub auth

### ISSUE THREAD

**Issue by ernieyu** [CodeMontageHQ/codemontage#148]
**Description**
I created an account for Coder Day and signed on through GitHub.  Then I tried to set a separate CM account password and couldn't.  If I remove GitHub auth, then I can't use my CM account at all.  I'm not sure that's a good thing.

**Ask**
Allow users to remove GitHub authorization while still maintaining their CodeMontage account.

**To Do**
- [ ] #303

**Comment by courte** [comment]
This issue should be resolved by #303.
