### ISSUE TITLE
Make form validation failure alerts more obvious

### ISSUE THREAD

**Issue by DBNess** [CodeMontageHQ/codemontage#170]
### Make form validation failure alerts more obvious
For example, on the [project submission page](http://www.codemontage.com/organizations/new), if you submit without a GitHub organization (labeled Organization GitHub Username here), you get an awkward next-line message of "can't be blank" that is indistinguishable from the next field's label.

![codemontageorgsubmissionpublic-23](https://f.cloud.github.com/assets/226228/2059445/a1a52ab0-8bae-11e3-91c3-b1da992bb269.png)

**Comment by courte** [comment]
This is related to #259 and has already been mostly resolved by other work (inclusion of the ClientSideValidations gem and reconfiguring of this form).
