### ISSUE TITLE
Restrict Duplicate Favorite Projects

### ISSUE THREAD

**Issue by DBNess** [CodeMontageHQ/codemontage#224]
There are currently no backend restrictions preventing duplicate projects saved by the same user, so if there are any frontend bugs like #220 we get messes like this one, submitted by @hiccuped:

![usabilityerror2](https://f.cloud.github.com/assets/6438777/2430257/9f98ac62-acc7-11e3-9fd2-ae47517edc1b.PNG)

Let's enforce the rule that a user can only save a project as a favorite once.

**Comment by courte** [comment]
Thanks, @steverob!

**Comment by courte** [comment]
Reopened for ops purposes but will be closed when #275 code is fully merged to production and root master.
