### ISSUE TITLE
Design Women Coders Dinner Series Landing Page

### ISSUE THREAD

**Issue by DBNess** [CodeMontageHQ/codemontage#241]
#### Follow-up to #237 Add Women Coders Dinners to Events Dropdown
**Create a new landing page** / Add a view for the Women Coders Dinner series, which will require some UI finesse and more copy. Once this is all set, we can update the link in the header nav events dropdown to direct to this page.

Awesome assets by @bmartinstudio are available [on Google Drive](https://drive.google.com/a/codemontage.com/#folders/0Bwkh7IDucSYNWWhLalEyamZ1WWc)

Use the Coder Day of Service page for inspiration: https://www.codemontage.com/coder_day

![codemontageeventsdropdown](https://cloud.githubusercontent.com/assets/226228/3387868/0f9a649c-fc82-11e3-9b7f-492d30f06663.png)

**Comment by courte** [comment]
This is no longer immediately necessary, although creating related events views might be helpful in the future.
