### ISSUE TITLE
Add Hound for Automated Ruby Style Checking

### ISSUE THREAD

**Issue by DBNess** [CodeMontageHQ/codemontage#290]
As suggested by @acrogenesis in #280, we're set up to run [Hound](https://houndci.com) from a GitHub permissions perspective. We now need to set up the codebase according to [Thoughtbot's Hound Configuration instructions](https://houndci.com/configuration):

Ruby

> To enable Ruby style checking, add the following to .hound.yml in the root of your project
```
ruby:
  enabled: true
```
> Hound uses [RuboCop](https://github.com/bbatsov/rubocop) internally so you can configure Hound by adding a [RuboCop config](https://github.com/bbatsov/rubocop/blob/master/config/enabled.yml) to your project and adding the following to .hound.yml in the root of your project.
```
ruby:
  enabled: true
  config_file: config/.rubocop.yml
```

**Comment by courte** [comment]
Handled by #300.
