### ISSUE TITLE
Fix mission statement on mobile devices

### ISSUE THREAD

**Issue by courte** [CodeMontageHQ/codemontage#321]
On mobile, the mission statement looks a bit oogly:
![screenshot_2015-01-26-14-28-38](https://cloud.githubusercontent.com/assets/2766324/5906968/96cb948c-a569-11e4-8119-18bc1c3130de.png)

Adjusting the styling for smaller devices would be _awesome_!!

**Comment by lixonic** [comment]
its better to hide the curly braces and give those spans a 100% width. 

![codemontage](https://cloud.githubusercontent.com/assets/934220/5914312/645379ba-a619-11e4-8972-eb0e975e9342.png)
