### ISSUE TITLE
Move Event Page Top RSVP Button Above "Join Us"

### ISSUE THREAD

**Issue by DBNess** [CodeMontageHQ/codemontage#324]
![rsvpbelowjoinus_eventpage](https://cloud.githubusercontent.com/assets/226228/5927111/7333445e-a63e-11e4-90bb-29ebd5cb8f29.jpg)

**Comment by thefenry** [comment]
@DBNess I made the Changes for this issue. If you need me to change anything else on this commit let me know. Here is what it looks like now:

![image](https://cloud.githubusercontent.com/assets/5784034/6089842/0b7dcfea-ae1e-11e4-9ee3-df6aec9fe3dd.png)

**Comment by courte** [comment]
Fixed by @thefenry's #331.
