### ISSUE TITLE
Incorrect Link for Code For America API Tasks

### ISSUE THREAD

**Issue by thatkaiguy** [CodeMontageHQ/codemontage#353]
![screen shot 2015-02-28 at 11](https://cloud.githubusercontent.com/assets/2458971/6427111/1d0661a8-bf3c-11e4-9cd6-6d44d10bc004.jpg)

This link doesn't work currently. Seems link is duplicated. Please change to 

https://github.com/codeforamerica/cfapi/issues

**Comment by DBNess** [comment]
Thanks so much @thatkaiguy! This is fixed now :heavy_check_mark: :+1:
