### ISSUE TITLE
Update Password Recovery Email Copy

### ISSUE THREAD

**Issue by courte** [CodeMontageHQ/codemontage#381]
**Description**
Our current password recovery email lacks the CodeMontage voice. We would like to update it with a tone that engages the user and improves their day in some small way.

![screenshot 2015-04-06 17 01 36](https://cloud.githubusercontent.com/assets/2766324/7050158/4cb49134-dded-11e4-91fd-00eecc892f89.png)

**Ask / To Do**
- [ ] Update the email language to better fit CodeMontage voice

**Comment by JTorr** [comment]
Submitted pull request.

**Comment by courte** [comment]
Thanks again, @JTorr! :clap: :confetti_ball:
