### ISSUE TITLE
Past Events Don't Display Without Upcoming Events

### ISSUE THREAD

**Issue by courte** [CodeMontageHQ/codemontage#390]
**Description**
Currently, when there are no upcoming events in the database, the events index looks like this:
![screenshot 2015-04-28 16 16 57](https://cloud.githubusercontent.com/assets/2766324/7379646/517d926a-edc4-11e4-8210-c05fca94737d.png)

**Ask / To Do**
- [ ] Update the conditional logic of the events index view to show past events, when upcoming events aren't available but past events are.
- [ ] Confirm that the "Oops" message still shows when there are no events available.

**Additional Info**
Be sure to use Foundation 4 standards wherever necessary.

**Comment by aliyeysides** [comment]
I'm trying to make a pull request but it keeps throwing me an error saying permission denied to aliyeysides. I thought maybe it was this http://stackoverflow.com/questions/7438313/pushing-to-git-returning-error-code-403-fatal-http-request-failed and I tried that approach but that didn't fix anything. Courte, you know I suck with git :-1:

**Comment by aliyeysides** [comment]
bump

**Comment by courte** [comment]
Hi, @aliyeysides! It doesn't look like you've created a fork of the project. Because you don't have access to CodeMontageHQ, you won't be able to make pull requests directly. Instead, create a fork of the CodeMontage codebase, use `git remote` to add your fork as a remote location, and push up to your fork. Then make your pull request through GitHub.

I hope that helps!
