### ISSUE TITLE
README specifies wrong ruby version

### ISSUE THREAD

**Issue by buck3000** [CodeMontageHQ/codemontage#398]
Description
Very minor but the README currently states that ruby 2.0.0 is specified in the Gemfile when it is actually 2.1.5

Ask
Change the README to make it accurate. Sorry if this is annoying, I'll contribute to real issues also (trying to get back in the open source game over here.)

To Do:
Edit that sentence.

Sincerely, 
The Human Equivalent of the 💯 emoji

P.S. Miss you Court.

**Comment by courte** [comment]
:heart_eyes: @buck3000, you rock!
